# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64

archives:
- replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
-
  vendor: "avtobiografia.com"
  homepage: "https://github.com/aquilax/daily-checklist"
  maintainer: "Evgeniy Vasilev <aquilax@gmail.com>"
  description: "Markdown checklist processor"
  license: "MIT"
  replacements:
    amd64: 64bit
    386: 32bit
  formats:
    - deb
    - rpm
